### ISSUE TITLE
Halite::RakeHelper.install_tasks is missing

### ISSUE THREAD

**Issue by eedwards-sk** [poise/halite#11]
Documentation describes using Halite::RakeHelper.install_tasks, but this method no longer exists.

**Comment by eedwards-sk** [comment]
As a workaround, rather than using `require 'halite/rake_tasks'`, I can do this:

```
require 'halite/rake_helper'

Halite::RakeHelper.install(
    gem_name: 'my_gem_name',
    base: "#{File.expand_path File.dirname(__FILE__)}"
)
```

**Comment by coderanger** [comment]
Thanks for the heads up, I fixed the readme.
