### ISSUE TITLE
cheftie.rb and entry points

### ISSUE THREAD

**Issue by vancluever** [poise/halite#2]
Hey Noah,

Can this be documented a bit?

https://github.com/poise/halite/blob/03c45888c5a9cc2ed59df13f25c8879f3648dd13/lib/halite/converter/libraries.rb#L61

I had to reverse-engineer this from `poise-service` to make the `ssh_keygen` provider I'm working on work.

**Comment by coderanger** [comment]
I'm holding on documenting it a bunch because I think it is going to change at least somewhat. The [Chef RFC](https://github.com/chef/chef-rfc/pull/160) for handing gem dependencies is probably going to go with the Rails-style of requiring the gem name and driving everything from there.

**Comment by vancluever** [comment]
Sounds good. At the very least this issue can serve as a bit of a hint for others until then ;)

**Comment by coderanger** [comment]
The pattern will look similar to rails plugins (which was the origin of the `cheftie` name), but with an explicit `require 'mygem/cheftie' if defined?(Chef)` to allow loading inside and outside Chef.

**Comment by vancluever** [comment]
Gotcha. Reading up on that now (http://api.rubyonrails.org/classes/Rails/Railtie.html), gives me a better idea of how to organize the gem. Also thanks for the link on the RFC, good to read up on things to come.

**Comment by lamont-granquist** [comment]
The RFC:

https://github.com/chef/chef-rfc/blob/master/rfc060-metadata-gem-installation.md

Is being worked on here:

https://github.com/chef/chef/pull/4478

Its just using bundler syntax now so `gem 'whatever', require: 'whatever/cheftie'` can be used to supply your own entrypoint (or name it something other than cheftie, doesn't matter...)

i think if you have git pre-installed on your image that checking out github branches would even work and other insane things i probably haven't thought about...

**Comment by vancluever** [comment]
Hey @coderanger, closing this one as it's pretty dormant now. I'm sure you're tracking anything that needs to be changed in halite to address this otherwise when the time comes :)
