### ISSUE TITLE
README.md Chef Version Errata

### ISSUE THREAD

**Issue by eedwardsdisco** [poise/halite#6]
I believe this example in README.md should be changed from `spec.metadata[halite_dependencies]` to  `spec.metadata[halite_chef_version]`

Original:

## Chef Version

By default cookbooks will be generated with `chef_version '~> 12'` to require
Chef 12.x. This can be overridden using the `halite_chef_version` metadata field:

```ruby
Gem::Specification.new do |spec|
  spec.metadata['halite_dependencies'] = '>= 12.0.0'
end
```

Modified:

## Chef Version

By default cookbooks will be generated with `chef_version '~> 12'` to require
Chef 12.x. This can be overridden using the `halite_chef_version` metadata field:

```ruby
Gem::Specification.new do |spec|
  spec.metadata['halite_chef_version'] = '>= 12.0.0'
end
```

**Comment by coderanger** [comment]
Good catch! Copy-paste error probably :(
