### ISSUE TITLE
Feature Request: Support 'supports' for generated metadata.rb

### ISSUE THREAD

**Issue by eedwardsdisco** [poise/halite#7]
As a Halite Gem Author, targeting a specific Platform and or Platform Version, I want to specify the value or values for the `supports` field, and have those values appear within the generated `metadata.rb` file.

Example use cases:

1) Writing a Library Halite Gem (Cookbook) for the Windows Platform

I want `supports 'windows'` to appear in my generated `metadata.rb` file.

2) Writing a Library Halite Gem (Cookbook) for the Ubuntu 14.04 Platform

I want `supports 'ubuntu', '= 14.04'` to appear in my generated `metadata.rb` file.

External reference: https://docs.chef.io/config_rb_metadata.html 'supports'

**Comment by coderanger** [comment]
The only thing that uses this field is a minor UI element in Supermarket so I'm not really inclined to add a lot of complexity to support it. Better to put what platforms you support in more detail in the README or other documentation.

**Comment by eedwardsdisco** [comment]
Thanks @coderanger - I'll understand if you close this as a 'won't fix', then.

I mainly opened it since I started chasing down `supports` as an option after running into what I described in https://github.com/poise/halite/issues/8 and abandoning using `provides`.

I'm trying to leverage as much baked in chef platform restriction functionality as I can before having to add platform checks everywhere in my code. The `provides` feature seems to work well for this, but is hitting the case described in the above linked issue.

**Comment by coderanger** [comment]
I'm happy to leave the issue open so others can weigh in, and if someone else submits a PR that is well built I would probably merge it, just not something I would spend a lot of time on myself. I think you assume that Chef itself uses this field, it does not. It is completely ignored by Chef, only Supermarket uses it and only for the little OS icons on the details pane.

**Comment by coderanger** [comment]
This was added in 1.7 via `spec.metadata['platforms'] = 'ubuntu centos'` or similar.
