### ISSUE TITLE
Feature Request: Support platform options for ChefSpec integration

### ISSUE THREAD

**Issue by eedwardsdisco** [poise/halite#8]
As a Halite Gem / Poise Resource Author, I would like to create a Halite Library Gem with a Resource that is specific to a Platform or Platform Version, and use the Halite ChefSpec integration to test it.

Currently, within a poise-based resource, if I specify additional options on my resource for a specific platform, e.g.:

```
module MyResource
  class Resource < Chef::Resource
    include Poise
    provides(:my_resource, os: 'windows')
    actions(:install)
  end
end
```

and later attempt to chefspec test it within the same gem:

```
describe MyResource::Resource do
  describe ':install' do
    context 'on windows server 2012R2' do
      recipe do
        my_resource 'myresource' do
          action :install
        end
      end

      let(:chefspec_options) { {platform: 'windows', version: '2012R2'} }

      step_into :my_resource

      it 'converges successfully' do
        expect{ chef_run }.not_to raise_error
      end

      it { is_expected.to install_my_resource('myresource') }
    end
  end
end
```

the resource is not found (snippet)

```
/.bundle/ruby/2.3.0/gems/chef-12.17.44/lib/chef/resource.rb:1544:in `resource_for_node': Cannot find a resource for my_resource on  version  (Chef::Exceptions::NoSuchResourceType)
	from /.bundle/ruby/2.3.0/gems/halite-1.3.0/lib/halite/spec_helper.rb:200:in `step_into'
```

**Comment by coderanger** [comment]
Unfortunately I don't think this could work as the lookup for the `step_into` happens outside of the context of a specific example so there is no node data available (specifically I do the lookup against `Chef::Node.new`). If this is a resource that is for Windows-specific stuff, it should still be declared as part of the DSL for all platforms. If it's something with Windows-specific behavior, it will work as long as you make sure there is a non-OS-specific variant available.

**Comment by eedwardsdisco** [comment]
@coderanger Wow you must be a night owl like me :)

Thanks for the insight. As I mentioned in #7, I'm just trying to avoid adding platform checks everywhere, and yes I'm working mostly with windows-only cookbooks in this case.

https://docs.chef.io/custom_resources.html#provides is where I got the idea:
>This allows you to use multiple custom resources files that provide the same resource to the user, but for different operating systems or operation system versions. With this you can eliminate the need for platform or platform version logic within your resources.

To your comment, though:
>If it's something with Windows-specific behavior, it will work as long as you make sure there is a non-OS-specific variant available.

Are you saying that as long as I have a resource that `provides(:resource_name)`, I can have another resource that `provides(:resource_name, os: 'windows')` within the same gem, and if I use chefspec to test it with `platform: 'windows', version: '2012R2'`, it will test the platform-specific behavior?

**Comment by coderanger** [comment]
Yep, technically you would have issues if the default and windows-only versions had different actions on them (specifically, the actions on the default would be the ones that get ChefSpec matchers automatically created for them) but that would be super confusing to most people too so I would probably not do that in general. There might also be some weirdness with the way the `unwrap_notifying_block` code works, but that can probably be fixed.

But again, even if a resource is Windows-specific you can and should still declare it for all platforms. You might want to make the provider map on Windows only and use the built-in noop provider for all other platforms but I generally find the explicit checks at the top of each action to be simpler and more clear.

**Comment by eedwardsdisco** [comment]
@coderanger Wow okay. Thanks Noah, that helps a lot!

Feel free to close this since it sounds un-actionable (but at least the discussion should be useful for anyone hitting this in the future).

(btw as an aside, I really appreciate all the work you're doing for the Chef community!)

**Comment by coderanger** [comment]
No problem, mapping per-OS resources (as opposed to providers) is a relatively recent feature in Chef and definitely not well supported in some places in the ecosystem. The flip side is that it took so long to add because it is only needed in a few very specific situations.
